# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

COPY ./app .

# Copy the requirements file into the container
COPY requirements.txt .

COPY . .

# Install dependencies
RUN pip install torch>=2.1 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117

RUN apt-get update && \
    apt-get install -y libgl1 espeak ffmpeg libncurses5-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# Install PyTorch and related packages
# RUN pip3 install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia

# Install Python dependencies
RUN apt-get update -y
RUN apt-get install ffmpeg -y
RUN apt-get update -y
RUN apt-get install  -y libncurses5-dev

#COPY ./requirements_venv_1.txt requirements.txt

RUN pip install -r requirements.txt 


# ENV PYTHONPATH=/vits_tts_app
ENV PYTHONPATH="/app/TTS:/app/TTS/TTS:/app:coqpit:/app/Trainer"

# Expose the port the app runs on
EXPOSE 8182

# Run the application
CMD ["python", "server.py"]
